// Flutter icons AppIcons
// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  AppIcons
//      fonts:
//       - asset: fonts/AppIcons.ttf
//

import 'package:flutter/widgets.dart';

class AppIcons {
  const AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const accountswitcher = IconData(0xe800, fontFamily: _kFontFam);
  static const accountwallet = IconData(0xe801, fontFamily: _kFontFam);
  static const addcontact = IconData(0xe802, fontFamily: _kFontFam);
  static const appia = IconData(0xe803, fontFamily: _kFontFam);
  static const at = IconData(0xe804, fontFamily: _kFontFam);
  static const back = IconData(0xe805, fontFamily: _kFontFam);
  static const backupseed = IconData(0xe806, fontFamily: _kFontFam);
  static const btc = IconData(0xe80a, fontFamily: _kFontFam);
  static const changerepresentative = IconData(0xe80b, fontFamily: _kFontFam);
  static const close = IconData(0xe80c, fontFamily: _kFontFam);
  static const contact = IconData(0xe80d, fontFamily: _kFontFam);
  static const currency = IconData(0xe80e, fontFamily: _kFontFam);
  static const dotemtpy = IconData(0xe80f, fontFamily: _kFontFam);
  static const dotfilled = IconData(0xe810, fontFamily: _kFontFam);
  static const export = IconData(0xe811, fontFamily: _kFontFam);
  static const fingerprint = IconData(0xe812, fontFamily: _kFontFam);
  static const forward = IconData(0xe813, fontFamily: _kFontFam);
  static const import = IconData(0xe814, fontFamily: _kFontFam);
  static const importwallet = IconData(0xe815, fontFamily: _kFontFam);
  static const info = IconData(0xe816, fontFamily: _kFontFam);
  static const language = IconData(0xe817, fontFamily: _kFontFam);
  static const lock = IconData(0xe818, fontFamily: _kFontFam);
  static const logout = IconData(0xe819, fontFamily: _kFontFam);
  static const max = IconData(0xe81a, fontFamily: _kFontFam);
  static const newwallet = IconData(0xe820, fontFamily: _kFontFam);
  static const notifications = IconData(0xe821, fontFamily: _kFontFam);
  static const paste = IconData(0xe822, fontFamily: _kFontFam);
  static const received = IconData(0xe823, fontFamily: _kFontFam);
  static const scan = IconData(0xe824, fontFamily: _kFontFam);
  static const score = IconData(0xe825, fontFamily: _kFontFam);
  static const search = IconData(0xe826, fontFamily: _kFontFam);
  static const seed = IconData(0xe827, fontFamily: _kFontFam);
  static const sent = IconData(0xe828, fontFamily: _kFontFam);
  static const settings = IconData(0xe829, fontFamily: _kFontFam);
  static const share = IconData(0xe82a, fontFamily: _kFontFam);
  static const success = IconData(0xe82b, fontFamily: _kFontFam);
  static const swapcurrency = IconData(0xe82c, fontFamily: _kFontFam);
  static const theme = IconData(0xe82d, fontFamily: _kFontFam);
  static const timer = IconData(0xe82e, fontFamily: _kFontFam);
  static const transferfunds = IconData(0xe82f, fontFamily: _kFontFam);
  static const trashcan = IconData(0xe830, fontFamily: _kFontFam);
  static const walletpassword = IconData(0xe831, fontFamily: _kFontFam);
  static const warning = IconData(0xe832, fontFamily: _kFontFam);
  static const walletpassworddisabled = IconData(0xe833, fontFamily: _kFontFam);
  static const security = IconData(0xe834, fontFamily: _kFontFam);
}
