// Writes lib/dotk/dotk_registry_data.dart from the deployment manifests that
// @dotk/sdk ships (https://github.com/supertypo/dotk-sdk). Run from the
// repository root with a dotk-sdk checkout or the installed npm package:
//
//   dart run tool/gen_dotk_registry.dart ../dotk-sdk
//   dart run tool/gen_dotk_registry.dart node_modules/@dotk/sdk
//
// The dispatch tags are read from the manifest's ABI and never recomputed, and
// each template must reproduce the template hash the manifest pins.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:blake3_dart/blake3_dart.dart';

const _output = 'lib/dotk/dotk_registry_data.dart';

// Not part of the manifest: fixed by the card format of @dotk/sdk
const _cardValue = 50000000;
const _cardMagic = 'dotk';

const _networks = {
  'mainnet': (
    name: 'mainnet',
    siteUrl: 'https://dotk.name',
    prefix: 'kaspa',
  ),
  'testnet-10': (
    name: 'testnet10',
    siteUrl: 'https://tn10.dotk.name',
    prefix: 'kaspaTest',
  ),
};

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'usage: dart run tool/gen_dotk_registry.dart <dotk-sdk dir>',
    );
    exit(64);
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_dotk_registry.dart. Do not edit.')
    ..writeln('//')
    ..writeln(
      '// Source: @dotk/sdk src/generated/{mainnet,testnet-10}/genesis.ts',
    )
    ..writeln('// Regenerate: dart run tool/gen_dotk_registry.dart ../dotk-sdk')
    ..writeln()
    ..writeln("part of 'dotk_registry.dart';");

  for (final MapEntry(key: network, value: info) in _networks.entries) {
    final file = _manifestFile(args.single, network);
    final manifest = _readManifest(file);
    if (manifest['network'] != network) {
      throw StateError('${file.path} is for ${manifest['network']}');
    }

    final deed = manifest['deedAbi']['contracts']['DotkDeed'];
    final gap = manifest['gapAbi']['contracts']['DotkGap'];
    final deedBytecode = _bytecode(deed, manifest['deedTemplateHash'], 'deed');
    final gapBytecode = _bytecode(gap, manifest['gapTemplateHash'], 'gap');
    final deedSpan = deed['compiled']['state_span'];
    if (deedSpan['offset'] != 1 || deedSpan['len'] != 103) {
      throw StateError('DotkRegistry assumes the deed state at 1..104');
    }
    final gapSpan = gap['compiled']['state_span'];
    final params = manifest['params'] as Map<String, dynamic>;

    String tag(Map<String, dynamic> contract, String entry) {
      final tag = contract['entries'][entry]['dispatch_tag'] as String;
      if (!RegExp(r'^[0-9a-f]{8}$').hasMatch(tag)) {
        throw StateError('$entry has no four-byte dispatch tag');
      }
      return tag;
    }

    out
      ..writeln()
      ..writeln('const _${info.name} = _DotkDeployment(')
      ..writeln("  network: '$network',")
      ..writeln('  prefix: AddressPrefix.${info.prefix},')
      ..writeln("  siteUrl: '${info.siteUrl}',")
      ..writeln("  covenantId: '${manifest['registryCovenantId']}',")
      ..writeln("  deedTemplateHash: '${manifest['deedTemplateHash']}',")
      ..writeln("  gapTemplateHash: '${manifest['gapTemplateHash']}',")
      ..writeln('  gapStateOffset: ${gapSpan['offset']},')
      ..writeln('  gapStateLength: ${gapSpan['len']},')
      ..writeln("  splitTag: '${tag(gap, 'split')}',")
      ..writeln("  activateTag: '${tag(deed, 'activate')}',")
      ..writeln("  transferTag: '${tag(deed, 'transfer')}',")
      ..writeln("  devfundScriptPublicKey: '${params['devfund_spk']}',")
      ..writeln('  fee1ch: ${params['fee_1ch']},')
      ..writeln('  fee2ch: ${params['fee_2ch']},')
      ..writeln('  fee3ch: ${params['fee_3ch']},')
      ..writeln('  fee4ch: ${params['fee_4ch']},')
      ..writeln('  fee5plus: ${params['fee_5plus']},')
      ..writeln('  bond: ${params['bond']},')
      ..writeln('  deposit: ${params['deposit']},')
      ..writeln('  gapValue: ${params['gap_value']},')
      ..writeln('  cardValue: $_cardValue,')
      ..writeln('  tEvict: ${params['t_evict']},')
      ..writeln("  cardMagic: '$_cardMagic',")
      ..writeln('  deedBytecode:')
      ..write(_hexLines(deedBytecode))
      ..writeln('  gapBytecode:')
      ..write(_hexLines(gapBytecode))
      ..writeln(');');
  }

  File(_output).writeAsStringSync(out.toString());
  final format = Process.runSync('dart', ['format', _output]);
  if (format.exitCode != 0) {
    throw StateError('dart format failed: ${format.stderr}');
  }
  stdout.writeln('wrote $_output');
}

/// The manifest module in a checkout, or in the built npm package
File _manifestFile(String root, String network) {
  for (final path in [
    '$root/src/generated/$network/genesis.ts',
    '$root/dist/generated/$network/genesis.js',
  ]) {
    final file = File(path);
    if (file.existsSync()) return file;
  }
  throw StateError('No $network manifest under $root');
}

/// The module is `export default` followed by the manifest as JSON
Map<String, dynamic> _readManifest(File file) {
  const marker = 'export default ';
  final source = file.readAsStringSync();
  final start = source.indexOf(marker);
  if (start < 0) {
    throw StateError('${file.path} has no default export');
  }
  var json = source.substring(start + marker.length).trim();
  if (json.endsWith(';')) {
    json = json.substring(0, json.length - 1);
  }
  return jsonDecode(json) as Map<String, dynamic>;
}

Uint8List _bytecode(Map<String, dynamic> contract, String pinned, String what) {
  final compiled = contract['compiled'];
  final bytecode = Uint8List.fromList(List<int>.from(compiled['bytecode']));
  final int offset = compiled['state_span']['offset'];
  final int length = compiled['state_span']['len'];

  // The template hash covers the fixed bytes around the state span, each
  // prefixed by its length as a little-endian u64
  final prefix = bytecode.sublist(0, offset);
  final suffix = bytecode.sublist(offset + length);
  final preimage = BytesBuilder()
    ..add(_le64(prefix.length))
    ..add(prefix)
    ..add(_le64(suffix.length))
    ..add(suffix);
  if (_hex(blake3(preimage.takeBytes())) != pinned) {
    throw StateError('$what bytecode does not reproduce its template hash');
  }

  return bytecode;
}

Uint8List _le64(int value) =>
    (ByteData(8)..setUint64(0, value, Endian.little)).buffer.asUint8List();

String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

String _hexLines(Uint8List bytes) {
  final hex = _hex(bytes);
  final out = StringBuffer();
  for (var i = 0; i < hex.length; i += 72) {
    final end = i + 72 < hex.length ? i + 72 : hex.length;
    final last = end == hex.length;
    out.writeln("      '${hex.substring(i, end)}'${last ? ',' : ''}");
  }
  return out.toString();
}
